language: java
sudo: false
jdk:
- oraclejdk8
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_0784da404d61_key -iv $encrypted_0784da404d61_iv -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- ./gradlew jacocoTestReport coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a75d6db45b15877d1975
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
